### ISSUE TITLE
「日本語TeX開発コミュニティ」公式サイトをtexjporg.github.io へ移行

### ISSUE THREAD

**Issue by munepi** [texjporg/texjporg.github.io#11]
「日本語TeX開発コミュニティ」公式サイト texjp.org を texjporg.github.io へ移行したいと考えています。
具体的には、texjp.org（とwww.texjp.org）を、このGitHubカスタムページに向けます。
それゆえ、移行完了後、Webブラウザで texjp.org を閲覧すると、ここのページが表示されることになります。

本案はいかがでしょうか？

**Comment by aminophen** [comment]
良いと思います！

**Comment by munepi** [comment]
@aminophen 
今日の正午に、本件の作業を行いました。
 * [www.texjp.org](https://www.texjp.org/) は自動的に [texjp.org](https://texjp.org/) へ飛びます。
 * また、[http](http://texjp.org/) でアクセスされたら、強制的に [https](https://texjp.org/) に飛びます。

**Comment by Oklahoma1122** [comment]
```
- [ ] @aminophen 
```
