### ISSUE TITLE
活動内容に各種「サービス」を掲載

### ISSUE THREAD

**Issue by munepi** [texjporg/texjporg.github.io#8]
texjp.org の内容のうち、少なくとも「TeX Liveリポジトリ集」を `activities/README.md` 以下に記載したいと考えています。

> ## TeX Liveリポジトリ集
> このTeX Liveリポジトリ集 https://texlive.texjp.org/ では、おもに日本国内のTeXユーザのために、以下の各種リポジトリを提供しています。
>
>  * TeX Live 最新版の公式リポジトリtlnetミラーおよびtltexjp：current/
>  * TeX Live pretestの公式リポジトリtlnetミラー：pretest/
>  * TeX Live 2012 frozen以降の公式リポジトリtlnetならびに、その補助リポジトリtlptexlive（2015以前）、tltexjp（2016以降）の保管

「日本語 TeX 開発コミュニティの活動内容」の見出しに則れば、

 * TeX Wiki
 * メーリングリスト
 * TeX Liveリポジトリ集 （日本語TeXに必要、かつ、完全に自己完結した状態で保管 historic archive）

を

 * `activities/README.md` に直下に加筆
 * 「サービス」 として、 `activities/services.md` ページに新規に起こす
 
 のどちらかにしたいと思っています。

**Comment by aminophen** [comment]
書いていただいてありがとうございます。あまり分量が多くないようであれば，新規に起こしたページと行き来するよりは

> activities/README.md に直下に加筆

でもいいような気がしますが，お任せします。

**Comment by munepi** [comment]
@aminophen 
コメントをありがとうございます。

PR #10 のとおり、「サービス」の分量はあまりないですが、
「TeX Liveリポジトリ集」
の説明は、少なくともどこかに書いておく必要があると思っています。

思い切って、activities/README.md 直下に、「## サービス」を追加して、同「サービス」の内容を追記してしまいましょうか。

**Comment by aminophen** [comment]
> TeX Liveリポジトリ集の説明

おっしゃる通り，是非書いておいていただきたいです。

> activities/README.md 直下に、「## サービス」を追加して、同「サービス」の内容を追記

これでも良いと思います。ありがとうございます。
